### PR TITLE
Fix nested views in HDBDD

### LINKED ISSUE #1615: [Parsers] HDBDD views inside context
### Details
When a view is defined in nested context in hdbdd it is not parsed correctly.

Example:
```
namespace gstr2;

@Schema: 'ADMIN'
context ProductsWithManagedAss {
      Entity MyEntity { ... }
      context embedded {
          view myView { ... }
      }
}
```

Generates the following SQL: `VIEW "null"."gstr2::embedded.ProductsWithManagedAss.myView" AS SELECT myColumn FROM "gstr2::embedded.MyEntity" AS "ALIAS"`
The `ViewSymbol` after parsing does not have a schema set.

The generated SQL should be `VIEW "ADMIN"."gstr2::ProductsWithManagedAss.embedded.myView" AS SELECT myColumn FROM "gstr2::ProductsWithManagedAss.MyEntity" AS "ALIAS"`

### PR DESCRIPTION
**Pull request by d-velev**
This PR fixes the following issues:
- views in nested contexts not having their schema set
- full names of symbols in a context being in reverse order
- references to entities outside of a view's context not being resolved

closes #1615

### CODE REVIEW

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java [hunk 1]
```diff
@@ -383,11 +376,24 @@ private List<EntityElementSymbol> getStructuredTypeSubElements(FieldSymbol entit
...
+      EntityElementSymbol foreignKey) {
     XSKDataStructureHDBTableColumnModel columnModel = transformFieldSymbolToColumnModel(foreignKey, false);
     columnModel.setPrimaryKey(associationSymbol.isKey());
     columnModel.setNullable(!associationSymbol.isNotNull());
 
     return columnModel;
   }
+
+  private String getFullTableName(ViewSymbol dependingView, String tableName) {
+    if (tableName.equalsIgnoreCase(DUMMY_TABLE)) {
```
Comment (vmutafov) [inline modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java:389]: What is this `DUMMY_TABLE`?

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java [hunk 2]
```diff
@@ -383,11 +376,24 @@ private List<EntityElementSymbol> getStructuredTypeSubElements(FieldSymbol entit
...
+      return tableName.toUpperCase();
+    } else {
+      Symbol resolvedDependsOnTable = dependingView.getEnclosingScope().resolve(tableName);
+      if (resolvedDependsOnTable == null) {
+        throw new CDSRuntimeException(String.format("Could not resolve referenced entity: %s", tableName));
```
Comment (vmutafov) [inline modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java:394]: You can use string concatenation instead of `String::format`

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java [hunk 3]
```diff
@@ -499,7 +500,7 @@ public void enterSelectRule(SelectRuleContext ctx) {
     }
 
     if (ctx.dependsOnTable != null) {
-      selectSymbol.setDependsOnTable(handleStringLiteral(ctx.dependsOnTable.getText()));
+      selectSymbol.setDependsOnTable(handleStringLiteral(ctx.dependsOnTable.stream().map(RuleContext::getText).collect(Collectors.joining("."))));
```
Comment (vmutafov) [inline modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java:503]: Move the stream operation and `handleStringLiteral` into separate variables. Also, what does `handleStringLiteral` do?

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java [hunk 4]
```diff
@@ -721,6 +720,16 @@ private void validateTopLevelSymbol(Symbol symbol) {
     }
   }
 
+  private void setContextChildSchemas(ContextSymbol symbol, String schema) {
+    symbol.getSymbols().forEach((k, v) -> {
+      if (v instanceof ContextSymbol) {
```
Comment (vmutafov) [inline modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java:725]: Is there a need for double-checking the type?

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java [hunk 5]
```diff
@@ -40,17 +40,24 @@ public void define(Symbol sym) {
...
+    if(name.contains(".")){
+      String[] identifiers = name.split("\\.");
+      Symbol outerContext = findSymbol(identifiers[0]);
 
-    // if not here, check any enclosing com.sap.xsk.parser.hdbdd.symbols.scope
-    if (getEnclosingScope() != null) {
-      return getEnclosingScope().resolve(name);
-    }
+      return resolveByContextArray(identifiers, outerContext);
+    } else {
```
Comment (vmutafov) [inline modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java:48]: No need for explicit `else` here

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java [hunk 6]
```diff
@@ -40,17 +40,24 @@ public void define(Symbol sym) {
...
+        return symbol;
+      }
+
+      // if not here, check any enclosing com.sap.xsk.parser.hdbdd.symbols.scope
+      if (getEnclosingScope() != null) {
+        return getEnclosingScope().resolve(name);
+      }
 
-    return null; // not found
+      return null; // not found
```
Comment (vmutafov) [inline modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java:59]: Shouldn't we log somewhere?

**Review by vmutafov — CHANGES_REQUESTED** [review]

**Review by vmutafov — CHANGES_REQUESTED** [review]

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java (hunk 3 above)
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java:503]: I guess it removes quotes and escaped quotes in strings.

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java (hunk 4 above)
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java:725]: v is one of the symbols of a context, it could also be an entity or a view in which case we just need to set the schema.

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java [hunk 7]
```diff
@@ -61,4 +68,34 @@ public Map<String, Symbol> getSymbols() {
...
+      resolvedSymbol = currentScope.resolve(name);
+    }
+
+    return resolvedSymbol;
+  }
+
+  private Symbol resolveByContextArray(String [] contexts, Symbol outerContext) {
+    Symbol resolvedSymbol = outerContext;
+    for(int i = 1; i < contexts.length; i++){
+      if(outerContext instanceof ContextSymbol) {
```
[the remark this answers is not in the document]
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java:90]: The whole check can actually be omitted

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java (hunk 1 above)
Comment (d-velev) [reply modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java:390]: There was a comment that explains this, I've added it again.

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java (hunk 6 above)
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java]: Not sure about logging, I think the cases in which we get null here handle it in some sort of way

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbdd/XSKHdbddParser.java [hunk 8]
```diff
@@ -84,15 +84,21 @@ public XSKDataStructureModel parse(XSKDataStructureParametersModel parametersMod
         this.symbolTable.clearSymbolsByFullName();
         this.symbolTable.clearEntityGraph();
         this.symbolTable.clearViewGraph();
-        throw new XSKDataStructuresException(e.getMessage());
+        throw new XSKDataStructuresException(e);
```
Comment (MarinHadzhiev) [inline modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbdd/XSKHdbddParser.java:87]: Add exception message and information about the file that cannot be parsed - location and anything that will help to identify and debug the problem

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java [hunk 9]
```diff
@@ -169,16 +170,7 @@ public String traverseSelectStatements(ViewSymbol viewSymbol, List<String> alias
...
-        // Check if the dependant table name is DUMMY. This is a reserved table name for hana dummy tables. We make sure to make it in uppercase
-        if (dependsOnTable.equalsIgnoreCase(DUMMY_TABLE)) {
-          dependsOnTable = dependsOnTable.toUpperCase();
-        } else {
-          String dependsOnTableFullName = fullTableNameBuilderFromViewSymbol(dependsOnTable, viewSymbol);
-          // Replace the short name in the select columns with the full name
-          selectColumns = replaceWithQuotes(selectColumns, dependsOnTable, dependsOnTableFullName);
-          // Set the dependant table to be with the full name
-          dependsOnTable = dependsOnTableFullName;
-        }
```
Comment (MarinHadzhiev) [inline modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java:181]: why did you delete this logic? What about the cases that are missing now?

**Review by MarinHadzhiev — CHANGES_REQUESTED** [review]

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java (hunk 9 above)
Comment (d-velev) [reply modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java:181]: This was moved to a private method called `getFullTableName`

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java (hunk 4 above)
Comment (vmutafov) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java:727]: But why is there a need to check it again in this method? There is already an `instanceof` check where this method is called

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java [hunk 10]
```diff
@@ -61,4 +70,36 @@ public Map<String, Symbol> getSymbols() {
...
+
+      currentScope = currentScope.getEnclosingScope();
+      resolvedSymbol = currentScope.resolve(name);
+    }
+
+    return resolvedSymbol;
+  }
+
+  private Symbol resolveByFullSymbolName(String[] contexts, Symbol outerContext) {
+    if (outerContext instanceof ContextSymbol) {
```
Comment (vmutafov) [inline modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java:90]: Could you reverse this condition to `if (!(outerContext instanceof ContextSymbol))` and return `null` there in order to reduce code nesting?

**Review by vmutafov — CHANGES_REQUESTED** [review]

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java (hunk 3 above)
Comment (vmutafov) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java]: Could you rename it to something more meaningful if it removes quotes?

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbdd/XSKHdbddParser.java (hunk 8 above)
Comment (d-velev) [reply modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbdd/XSKHdbddParser.java:87]: We do get such information, for instance: `"com.sap.xsk.parser.hdbdd.exception.CDSRuntimeException: Failed to parse file: gstr2/ITC_EXPIRED_CONFIG.hdbdd. Error at line: 6  - Before an entity element declaration only the 'key' keyword is allowed"`

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java [hunk 11]
```diff
@@ -61,4 +70,36 @@ public Map<String, Symbol> getSymbols() {
...
+      Symbol resolvedSymbol = outerContext;
+
+      for (int i = 1; i < contexts.length; i++) {
```
[the remark this answers is not in the document]
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/symbols/context/ContextSymbol.java:93]: We have to start from the second element since the first one is already resolved

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java (hunk 4 above)
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java:727]: This is done for each of the context symbol's children, not the parameter `symbol` itself.

File: modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java (hunk 3 above)
Comment (d-velev) [reply modules/parsers/parser-hdbdd/src/main/java/com/sap/xsk/parser/hdbdd/custom/ArtifactDefinitionListener.java]: This wasn't implemented by me, I can't think of a more semantically appropriate name without making it sound weird

File: modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java (hunk 9 above)
Comment (MarinHadzhiev) [reply modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/transformer/hdbdd/HdbddTransformer.java:220]: but what about line 178?

**Review by MarinHadzhiev — APPROVED** [review]

**Review by vmutafov — APPROVED** [review]
